<%inherit file="base.mako" />
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    ${self.head()}
    <meta http-equiv="X-UA-Compatible" content="IE=9"/>
    <meta name="generator" content="Doxygen 1.8.3.1"/>
    <title>openFrameworks: Class Index</title>
    <link href="tabs.css" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" src="dynsections.js"></script>
    <link href="search/search.css" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" src="search/search.js"></script>
    <script type="text/javascript">
      $(document).ready(function() { searchBox.OnSelectItem(0); });
    </script>
    <link href="doxygen.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div id="content">
      ${self.header()}
      <div id="body-wrap">
      		<div class="page-wide">
	            <div class="page-left-split">
           		    <h1 class="documentation">reference</h1> <ul class="docsadvanced"><li><a href="/documentation">basic</a></li> <li><a  class="active" href="/doxygen/annotated.html">advanced</a></li> </ul>
           		</div>
		        <div class="page-right-narrow">
			        <p>This documentation is automatically generated from the openFrameworks source code using doxygen and refers to the most recent release, version <strong>${bf.config.currentVersion}</strong>.</p>
		        </div>
       		</div>
      		<div class="page-wide">
      		    <div class="doxy-mainmenu">
<!-- Generated by Doxygen 1.8.4 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.html"><span>Related&#160;Pages</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.html"><span>Class&#160;List</span></a></li>
      <li><a href="classes.html"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.html"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.html"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-methods">Protected Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="classof3d_primitive-members.html">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">of3dPrimitive Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p><code>#include &lt;<a class="el" href="of3d_primitives_8h_source.html">of3dPrimitives.h</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for of3dPrimitive:</div>
<div class="dyncontent">
 <div class="center">
  <img src="classof3d_primitive.png" usemap="#of3dPrimitive_map" alt=""/>
  <map id="of3dPrimitive_map" name="of3dPrimitive_map">
<area href="classof_node.html" alt="ofNode" shape="rect" coords="347,0,476,24"/>
<area href="classof_box_primitive.html" alt="ofBoxPrimitive" shape="rect" coords="0,112,129,136"/>
<area href="classof_cone_primitive.html" alt="ofConePrimitive" shape="rect" coords="139,112,268,136"/>
<area href="classof_cylinder_primitive.html" alt="ofCylinderPrimitive" shape="rect" coords="278,112,407,136"/>
<area href="classof_ico_sphere_primitive.html" alt="ofIcoSpherePrimitive" shape="rect" coords="417,112,546,136"/>
<area href="classof_plane_primitive.html" alt="ofPlanePrimitive" shape="rect" coords="556,112,685,136"/>
<area href="classof_sphere_primitive.html" alt="ofSpherePrimitive" shape="rect" coords="695,112,824,136"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:af2f40819bcf5c442496dab452fa91eae"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#af2f40819bcf5c442496dab452fa91eae">of3dPrimitive</a> ()</td></tr>
<tr class="separator:af2f40819bcf5c442496dab452fa91eae"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afff7a25964107e95f581b00ab8f83b98"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#afff7a25964107e95f581b00ab8f83b98">~of3dPrimitive</a> ()</td></tr>
<tr class="separator:afff7a25964107e95f581b00ab8f83b98"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a67735f4a20c6992f3ee1e95f023bfb02"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a67735f4a20c6992f3ee1e95f023bfb02">of3dPrimitive</a> (const <a class="el" href="classof3d_primitive.html">of3dPrimitive</a> &amp;mom)</td></tr>
<tr class="separator:a67735f4a20c6992f3ee1e95f023bfb02"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a190fc8fe46186cdb4bca8a4206046bfd"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof3d_primitive.html">of3dPrimitive</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a190fc8fe46186cdb4bca8a4206046bfd">operator=</a> (const <a class="el" href="classof3d_primitive.html">of3dPrimitive</a> &amp;mom)</td></tr>
<tr class="separator:a190fc8fe46186cdb4bca8a4206046bfd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad90951485c94c5c6c4e5dcd2e9051d9e"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#ad90951485c94c5c6c4e5dcd2e9051d9e">mapTexCoords</a> (float u1, float v1, float u2, float v2)</td></tr>
<tr class="separator:ad90951485c94c5c6c4e5dcd2e9051d9e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2ba2e23c9c13586cf7d7e2f29d193f1a"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a2ba2e23c9c13586cf7d7e2f29d193f1a">mapTexCoordsFromTexture</a> (<a class="el" href="classof_texture.html">ofTexture</a> &amp;inTexture)</td></tr>
<tr class="separator:a2ba2e23c9c13586cf7d7e2f29d193f1a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a587142eae702b12669a369a8130bb3ad"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_mesh.html">ofMesh</a> *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a587142eae702b12669a369a8130bb3ad">getMeshPtr</a> ()</td></tr>
<tr class="separator:a587142eae702b12669a369a8130bb3ad"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a83846bb15db870f7bca03b653e33ebd4"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_mesh.html">ofMesh</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a83846bb15db870f7bca03b653e33ebd4">getMesh</a> ()</td></tr>
<tr class="separator:a83846bb15db870f7bca03b653e33ebd4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a65f754444368b9a7e3c96d7032106ff9"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_vec4f.html">ofVec4f</a> *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a65f754444368b9a7e3c96d7032106ff9">getTexCoordsPtr</a> ()</td></tr>
<tr class="separator:a65f754444368b9a7e3c96d7032106ff9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a646d09ddf195b48811ffada059f23ff7"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_vec4f.html">ofVec4f</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a646d09ddf195b48811ffada059f23ff7">getTexCoords</a> ()</td></tr>
<tr class="separator:a646d09ddf195b48811ffada059f23ff7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a20f8e5bc3113ec162d258b24379fca9c"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a20f8e5bc3113ec162d258b24379fca9c">hasScaling</a> ()</td></tr>
<tr class="separator:a20f8e5bc3113ec162d258b24379fca9c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a396eb4253f091751efa9eb63d0885f66"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a396eb4253f091751efa9eb63d0885f66">hasNormalsEnabled</a> ()</td></tr>
<tr class="separator:a396eb4253f091751efa9eb63d0885f66"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad4bb43ba66c67264d2a6298530ab20a7"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#ad4bb43ba66c67264d2a6298530ab20a7">enableNormals</a> ()</td></tr>
<tr class="separator:ad4bb43ba66c67264d2a6298530ab20a7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aabe60b72a80f9bb01be030d0d17d9f85"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#aabe60b72a80f9bb01be030d0d17d9f85">enableTextures</a> ()</td></tr>
<tr class="separator:aabe60b72a80f9bb01be030d0d17d9f85"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a328453a01022687422d1527414afc8b3"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a328453a01022687422d1527414afc8b3">enableColors</a> ()</td></tr>
<tr class="separator:a328453a01022687422d1527414afc8b3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a464b2f4f9b2132b395061aa44080b75b"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a464b2f4f9b2132b395061aa44080b75b">disableNormals</a> ()</td></tr>
<tr class="separator:a464b2f4f9b2132b395061aa44080b75b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac13bb4ace465b00abec3fd9f73825121"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#ac13bb4ace465b00abec3fd9f73825121">disableTextures</a> ()</td></tr>
<tr class="separator:ac13bb4ace465b00abec3fd9f73825121"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8f15788c4d116426957853a604fb9b6f"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a8f15788c4d116426957853a604fb9b6f">disableColors</a> ()</td></tr>
<tr class="separator:a8f15788c4d116426957853a604fb9b6f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0f570870b5d7e287570fe4ea0d29a3e2"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a0f570870b5d7e287570fe4ea0d29a3e2">removeMesh</a> (int index)</td></tr>
<tr class="separator:a0f570870b5d7e287570fe4ea0d29a3e2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3d372c0c126f770b79e1e55e123ed4cd"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a3d372c0c126f770b79e1e55e123ed4cd">removeTexture</a> (int index)</td></tr>
<tr class="separator:a3d372c0c126f770b79e1e55e123ed4cd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab4b8f885982752b1ce14af3da8144ecc"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#ab4b8f885982752b1ce14af3da8144ecc">clear</a> ()</td></tr>
<tr class="separator:ab4b8f885982752b1ce14af3da8144ecc"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a56bfd9c16069a94afcd1ff827dba5d06"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a56bfd9c16069a94afcd1ff827dba5d06">drawVertices</a> ()</td></tr>
<tr class="separator:a56bfd9c16069a94afcd1ff827dba5d06"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7c85104c7efddb16ba7e07d4dcb1e85e"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a7c85104c7efddb16ba7e07d4dcb1e85e">drawWireframe</a> ()</td></tr>
<tr class="separator:a7c85104c7efddb16ba7e07d4dcb1e85e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3c6ed146402e3ac7dbc7a614086000b7"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a3c6ed146402e3ac7dbc7a614086000b7">drawFaces</a> ()</td></tr>
<tr class="separator:a3c6ed146402e3ac7dbc7a614086000b7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa8dd648110dd9cef3e14ce192d2b208e"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#aa8dd648110dd9cef3e14ce192d2b208e">draw</a> ()</td></tr>
<tr class="separator:aa8dd648110dd9cef3e14ce192d2b208e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af9eb1d12247144a53e8031a54d5f0c19"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#af9eb1d12247144a53e8031a54d5f0c19">draw</a> (<a class="el" href="of_g_l_utils_8h.html#a6beb1fbbaba728909c78cda1eadfe28e">ofPolyRenderMode</a> renderType)</td></tr>
<tr class="separator:af9eb1d12247144a53e8031a54d5f0c19"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa1eb38eb45d5b233f66814fd639d1752"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#aa1eb38eb45d5b233f66814fd639d1752">drawNormals</a> (float length, bool bFaceNormals=false)</td></tr>
<tr class="separator:aa1eb38eb45d5b233f66814fd639d1752"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8827908140fd276554b65f6ab7bb4b77"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a8827908140fd276554b65f6ab7bb4b77">drawAxes</a> (float a_size)</td></tr>
<tr class="separator:a8827908140fd276554b65f6ab7bb4b77"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:addbf2820728f1df687d800ec9fed706a"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#addbf2820728f1df687d800ec9fed706a">setUseVbo</a> (bool useVbo)</td></tr>
<tr class="separator:addbf2820728f1df687d800ec9fed706a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa24eb5218bfaa8fcb605fc1362dfd4a4"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#aa24eb5218bfaa8fcb605fc1362dfd4a4">isUsingVbo</a> ()</td></tr>
<tr class="separator:aa24eb5218bfaa8fcb605fc1362dfd4a4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_classof_node"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_classof_node')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="classof_node.html">ofNode</a></td></tr>
<tr class="memitem:aa2b223ca1f8560ef193eb7bde666d758 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#aa2b223ca1f8560ef193eb7bde666d758">ofNode</a> ()</td></tr>
<tr class="separator:aa2b223ca1f8560ef193eb7bde666d758 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad0f916a28a08c95064e89bdc5131b923 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#ad0f916a28a08c95064e89bdc5131b923">~ofNode</a> ()</td></tr>
<tr class="separator:ad0f916a28a08c95064e89bdc5131b923 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad475e04b79cbd1528ae3c59adba0a7c2 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#ad475e04b79cbd1528ae3c59adba0a7c2">setParent</a> (<a class="el" href="classof_node.html">ofNode</a> &amp;<a class="el" href="classof_node.html#a9fa60edff25434ada1671e837335fbdf">parent</a>, bool bMaintainGlobalTransform=false)</td></tr>
<tr class="separator:ad475e04b79cbd1528ae3c59adba0a7c2 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa6c41c2d514797f04f162bb323cb4dfa inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#aa6c41c2d514797f04f162bb323cb4dfa">clearParent</a> (bool bMaintainGlobalTransform=false)</td></tr>
<tr class="separator:aa6c41c2d514797f04f162bb323cb4dfa inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a08d61ddc77fd655780a7c269756b7ecb inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_node.html">ofNode</a> *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a08d61ddc77fd655780a7c269756b7ecb">getParent</a> () const </td></tr>
<tr class="separator:a08d61ddc77fd655780a7c269756b7ecb inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a89350f61b536e5f64dc13682a6aee97d inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_vec3f.html">ofVec3f</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a89350f61b536e5f64dc13682a6aee97d">getPosition</a> () const </td></tr>
<tr class="separator:a89350f61b536e5f64dc13682a6aee97d inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a819b96492b11250d5682e7853c5b753c inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">float&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a819b96492b11250d5682e7853c5b753c">getX</a> () const </td></tr>
<tr class="separator:a819b96492b11250d5682e7853c5b753c inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1177cd7d07224c3690a4364684f1719f inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">float&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a1177cd7d07224c3690a4364684f1719f">getY</a> () const </td></tr>
<tr class="separator:a1177cd7d07224c3690a4364684f1719f inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aad7aed0da357927a7bfa1c5669fd9e64 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">float&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#aad7aed0da357927a7bfa1c5669fd9e64">getZ</a> () const </td></tr>
<tr class="separator:aad7aed0da357927a7bfa1c5669fd9e64 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a75af589eae2b502216acad4668edf43b inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_vec3f.html">ofVec3f</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a75af589eae2b502216acad4668edf43b">getXAxis</a> () const </td></tr>
<tr class="separator:a75af589eae2b502216acad4668edf43b inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6bf67ed85db5017a37aba4e3262e914a inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_vec3f.html">ofVec3f</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a6bf67ed85db5017a37aba4e3262e914a">getYAxis</a> () const </td></tr>
<tr class="separator:a6bf67ed85db5017a37aba4e3262e914a inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aecfc7c45671b9bb4757821e3a10dccb1 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_vec3f.html">ofVec3f</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#aecfc7c45671b9bb4757821e3a10dccb1">getZAxis</a> () const </td></tr>
<tr class="separator:aecfc7c45671b9bb4757821e3a10dccb1 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aaa10e7761bcbfc1c504c6312c52f833a inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_vec3f.html">ofVec3f</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#aaa10e7761bcbfc1c504c6312c52f833a">getSideDir</a> () const </td></tr>
<tr class="separator:aaa10e7761bcbfc1c504c6312c52f833a inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a884d1b02034ac8822415bbb43ac4dd5f inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_vec3f.html">ofVec3f</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a884d1b02034ac8822415bbb43ac4dd5f">getLookAtDir</a> () const </td></tr>
<tr class="separator:a884d1b02034ac8822415bbb43ac4dd5f inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae24a97f7de20c48a5f75d82fb12577cf inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_vec3f.html">ofVec3f</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#ae24a97f7de20c48a5f75d82fb12577cf">getUpDir</a> () const </td></tr>
<tr class="separator:ae24a97f7de20c48a5f75d82fb12577cf inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4f52fa48348f59307623c7a7bb4ef59f inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">float&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a4f52fa48348f59307623c7a7bb4ef59f">getPitch</a> () const </td></tr>
<tr class="separator:a4f52fa48348f59307623c7a7bb4ef59f inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a91b332c93dd0da7c289ffcc95ccc5a46 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">float&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a91b332c93dd0da7c289ffcc95ccc5a46">getHeading</a> () const </td></tr>
<tr class="separator:a91b332c93dd0da7c289ffcc95ccc5a46 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0336b1426c2bc493bc15a7093fb35b5a inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">float&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a0336b1426c2bc493bc15a7093fb35b5a">getRoll</a> () const </td></tr>
<tr class="separator:a0336b1426c2bc493bc15a7093fb35b5a inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae8ca41c6f9eac9a64d7c19a6811f66b5 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_quaternion.html">ofQuaternion</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#ae8ca41c6f9eac9a64d7c19a6811f66b5">getOrientationQuat</a> () const </td></tr>
<tr class="separator:ae8ca41c6f9eac9a64d7c19a6811f66b5 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a105586cd87594a6ab0841e39f474e70e inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_vec3f.html">ofVec3f</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a105586cd87594a6ab0841e39f474e70e">getOrientationEuler</a> () const </td></tr>
<tr class="separator:a105586cd87594a6ab0841e39f474e70e inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7dd2e9bbcc2c8ce02317892b40793a0f inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_vec3f.html">ofVec3f</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a7dd2e9bbcc2c8ce02317892b40793a0f">getScale</a> () const </td></tr>
<tr class="separator:a7dd2e9bbcc2c8ce02317892b40793a0f inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a282b3da0e8371db84ba64c9725794b17 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">const <a class="el" href="classof_matrix4x4.html">ofMatrix4x4</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a282b3da0e8371db84ba64c9725794b17">getLocalTransformMatrix</a> () const </td></tr>
<tr class="separator:a282b3da0e8371db84ba64c9725794b17 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a78a98aca9e6d389ae4918ad9783f3bf7 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_matrix4x4.html">ofMatrix4x4</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a78a98aca9e6d389ae4918ad9783f3bf7">getGlobalTransformMatrix</a> () const </td></tr>
<tr class="separator:a78a98aca9e6d389ae4918ad9783f3bf7 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4ad665eca93ee00d506d0c663d6dcddd inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_vec3f.html">ofVec3f</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a4ad665eca93ee00d506d0c663d6dcddd">getGlobalPosition</a> () const </td></tr>
<tr class="separator:a4ad665eca93ee00d506d0c663d6dcddd inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a427fce44ef9e64b50c223a42d057a700 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_quaternion.html">ofQuaternion</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a427fce44ef9e64b50c223a42d057a700">getGlobalOrientation</a> () const </td></tr>
<tr class="separator:a427fce44ef9e64b50c223a42d057a700 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a47c700c7791c41afb514a9949653540c inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_vec3f.html">ofVec3f</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a47c700c7791c41afb514a9949653540c">getGlobalScale</a> () const </td></tr>
<tr class="separator:a47c700c7791c41afb514a9949653540c inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aee04a17c179cb45f7e03f8518be8d0ad inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#aee04a17c179cb45f7e03f8518be8d0ad">setTransformMatrix</a> (const <a class="el" href="classof_matrix4x4.html">ofMatrix4x4</a> &amp;m44)</td></tr>
<tr class="separator:aee04a17c179cb45f7e03f8518be8d0ad inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6f5733da97701638ec9e089016d0381a inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a6f5733da97701638ec9e089016d0381a">setPosition</a> (float <a class="el" href="of_matrix4x4_8cpp.html#a202a282799ace8d7de6aa1f699ef546d">px</a>, float <a class="el" href="of_matrix4x4_8cpp.html#a7284a3e64f3c6d8d549a591c5208aedd">py</a>, float <a class="el" href="of_matrix4x4_8cpp.html#a3dc06ac98e72b809b5ff6daf0a442c37">pz</a>)</td></tr>
<tr class="separator:a6f5733da97701638ec9e089016d0381a inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae55d7884cc7193538fddd8071f533379 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#ae55d7884cc7193538fddd8071f533379">setPosition</a> (const <a class="el" href="classof_vec3f.html">ofVec3f</a> &amp;p)</td></tr>
<tr class="separator:ae55d7884cc7193538fddd8071f533379 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a72d4e80f9e3cc5356860669be45076e7 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a72d4e80f9e3cc5356860669be45076e7">setGlobalPosition</a> (float <a class="el" href="of_matrix4x4_8cpp.html#a202a282799ace8d7de6aa1f699ef546d">px</a>, float <a class="el" href="of_matrix4x4_8cpp.html#a7284a3e64f3c6d8d549a591c5208aedd">py</a>, float <a class="el" href="of_matrix4x4_8cpp.html#a3dc06ac98e72b809b5ff6daf0a442c37">pz</a>)</td></tr>
<tr class="separator:a72d4e80f9e3cc5356860669be45076e7 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a639c866edf3aac3192713dfcdbb2e992 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a639c866edf3aac3192713dfcdbb2e992">setGlobalPosition</a> (const <a class="el" href="classof_vec3f.html">ofVec3f</a> &amp;p)</td></tr>
<tr class="separator:a639c866edf3aac3192713dfcdbb2e992 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a732a883de750dcd157ba03a7a9432f57 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a732a883de750dcd157ba03a7a9432f57">setOrientation</a> (const <a class="el" href="classof_quaternion.html">ofQuaternion</a> &amp;q)</td></tr>
<tr class="separator:a732a883de750dcd157ba03a7a9432f57 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7e7460d86348bc31837271fe30e74b89 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a7e7460d86348bc31837271fe30e74b89">setOrientation</a> (const <a class="el" href="classof_vec3f.html">ofVec3f</a> &amp;eulerAngles)</td></tr>
<tr class="separator:a7e7460d86348bc31837271fe30e74b89 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac888a4aabc97bdfa86114079dcdf4832 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#ac888a4aabc97bdfa86114079dcdf4832">setGlobalOrientation</a> (const <a class="el" href="classof_quaternion.html">ofQuaternion</a> &amp;q)</td></tr>
<tr class="separator:ac888a4aabc97bdfa86114079dcdf4832 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a29db49b22f24505ca352ad90a0d9ffd6 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a29db49b22f24505ca352ad90a0d9ffd6">setScale</a> (float s)</td></tr>
<tr class="separator:a29db49b22f24505ca352ad90a0d9ffd6 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1edc7d654f34143e14a88423dce97c1d inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a1edc7d654f34143e14a88423dce97c1d">setScale</a> (float sx, float sy, float sz)</td></tr>
<tr class="separator:a1edc7d654f34143e14a88423dce97c1d inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0dc74f803d307c24e08b2e163295287b inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a0dc74f803d307c24e08b2e163295287b">setScale</a> (const <a class="el" href="classof_vec3f.html">ofVec3f</a> &amp;s)</td></tr>
<tr class="separator:a0dc74f803d307c24e08b2e163295287b inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a89949bfa32613379f65466be7514032a inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a89949bfa32613379f65466be7514032a">move</a> (float x, float y, float z)</td></tr>
<tr class="separator:a89949bfa32613379f65466be7514032a inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2c9fe659a2f8a45336d5ec385e7442ac inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a2c9fe659a2f8a45336d5ec385e7442ac">move</a> (const <a class="el" href="classof_vec3f.html">ofVec3f</a> &amp;offset)</td></tr>
<tr class="separator:a2c9fe659a2f8a45336d5ec385e7442ac inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a61fcc8f30420847847f62873a47cca8a inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a61fcc8f30420847847f62873a47cca8a">truck</a> (float amount)</td></tr>
<tr class="separator:a61fcc8f30420847847f62873a47cca8a inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad030cd8c55b9df3dbf2786347f62ad3b inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#ad030cd8c55b9df3dbf2786347f62ad3b">boom</a> (float amount)</td></tr>
<tr class="separator:ad030cd8c55b9df3dbf2786347f62ad3b inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8ab940d4c166064c8b2e3b4ab237917c inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a8ab940d4c166064c8b2e3b4ab237917c">dolly</a> (float amount)</td></tr>
<tr class="separator:a8ab940d4c166064c8b2e3b4ab237917c inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a674ca0b1cb71f609fadf8dba79106a72 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a674ca0b1cb71f609fadf8dba79106a72">tilt</a> (float degrees)</td></tr>
<tr class="separator:a674ca0b1cb71f609fadf8dba79106a72 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad8f671a39235404984fb84da35dd93ae inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#ad8f671a39235404984fb84da35dd93ae">pan</a> (float degrees)</td></tr>
<tr class="separator:ad8f671a39235404984fb84da35dd93ae inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6eabc08d0e5ec0f8e7b6d2931531e400 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a6eabc08d0e5ec0f8e7b6d2931531e400">roll</a> (float degrees)</td></tr>
<tr class="separator:a6eabc08d0e5ec0f8e7b6d2931531e400 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1334bc48d4dbbc8d769ce42ee82fdf96 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a1334bc48d4dbbc8d769ce42ee82fdf96">rotate</a> (const <a class="el" href="classof_quaternion.html">ofQuaternion</a> &amp;q)</td></tr>
<tr class="separator:a1334bc48d4dbbc8d769ce42ee82fdf96 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae5d336038ea9a78223218183bbc446f0 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#ae5d336038ea9a78223218183bbc446f0">rotate</a> (float degrees, const <a class="el" href="classof_vec3f.html">ofVec3f</a> &amp;v)</td></tr>
<tr class="separator:ae5d336038ea9a78223218183bbc446f0 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a567e36b8f19965cb37b093283f7fcf09 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a567e36b8f19965cb37b093283f7fcf09">rotate</a> (float degrees, float vx, float vy, float vz)</td></tr>
<tr class="separator:a567e36b8f19965cb37b093283f7fcf09 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a084b6a9cc56ae474be007ba4595c471d inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a084b6a9cc56ae474be007ba4595c471d">rotateAround</a> (const <a class="el" href="classof_quaternion.html">ofQuaternion</a> &amp;q, const <a class="el" href="classof_vec3f.html">ofVec3f</a> &amp;point)</td></tr>
<tr class="separator:a084b6a9cc56ae474be007ba4595c471d inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a99683f424fc89553cfbdab53d52a1e7f inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a99683f424fc89553cfbdab53d52a1e7f">rotateAround</a> (float degrees, const <a class="el" href="classof_vec3f.html">ofVec3f</a> &amp;axis, const <a class="el" href="classof_vec3f.html">ofVec3f</a> &amp;point)</td></tr>
<tr class="separator:a99683f424fc89553cfbdab53d52a1e7f inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a039b31630ea3fc3718da43e23ecd7ef3 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a039b31630ea3fc3718da43e23ecd7ef3">lookAt</a> (const <a class="el" href="classof_vec3f.html">ofVec3f</a> &amp;lookAtPosition, <a class="el" href="classof_vec3f.html">ofVec3f</a> upVector=<a class="el" href="classof_vec3f.html">ofVec3f</a>(0, 1, 0))</td></tr>
<tr class="separator:a039b31630ea3fc3718da43e23ecd7ef3 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a40809315f147738b1f8f991e6d58c753 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a40809315f147738b1f8f991e6d58c753">lookAt</a> (const <a class="el" href="classof_node.html">ofNode</a> &amp;lookAtNode, const <a class="el" href="classof_vec3f.html">ofVec3f</a> &amp;upVector=<a class="el" href="classof_vec3f.html">ofVec3f</a>(0, 1, 0))</td></tr>
<tr class="separator:a40809315f147738b1f8f991e6d58c753 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2a0989e1ed10fcbfea932ea305f064c1 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a2a0989e1ed10fcbfea932ea305f064c1">orbit</a> (float longitude, float latitude, float radius, const <a class="el" href="classof_vec3f.html">ofVec3f</a> &amp;centerPoint=<a class="el" href="classof_vec3f.html">ofVec3f</a>(0, 0, 0))</td></tr>
<tr class="separator:a2a0989e1ed10fcbfea932ea305f064c1 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8d0f25fffcba51783c5c9d53d87c4f82 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a8d0f25fffcba51783c5c9d53d87c4f82">orbit</a> (float longitude, float latitude, float radius, <a class="el" href="classof_node.html">ofNode</a> &amp;centerNode)</td></tr>
<tr class="separator:a8d0f25fffcba51783c5c9d53d87c4f82 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af5fc70fbfb7826ebca9ae9eaa7653db8 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#af5fc70fbfb7826ebca9ae9eaa7653db8">transformGL</a> () const </td></tr>
<tr class="separator:af5fc70fbfb7826ebca9ae9eaa7653db8 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9d09e55a671dae12c64b18215f2cd08c inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a9d09e55a671dae12c64b18215f2cd08c">restoreTransformGL</a> () const </td></tr>
<tr class="separator:a9d09e55a671dae12c64b18215f2cd08c inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ace344f081aa534670949ae9e03374626 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#ace344f081aa534670949ae9e03374626">resetTransform</a> ()</td></tr>
<tr class="separator:ace344f081aa534670949ae9e03374626 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a23a1ca114eeff7e8494cecee90002534 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a23a1ca114eeff7e8494cecee90002534">customDraw</a> ()</td></tr>
<tr class="separator:a23a1ca114eeff7e8494cecee90002534 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a13c85ec24bc0244ee7e32be7a63f2561 inherit pub_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a13c85ec24bc0244ee7e32be7a63f2561">draw</a> ()</td></tr>
<tr class="separator:a13c85ec24bc0244ee7e32be7a63f2561 inherit pub_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-methods"></a>
Protected Member Functions</h2></td></tr>
<tr class="memitem:a157ddb6ce88f87553e45c04b79fa7b85"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a157ddb6ce88f87553e45c04b79fa7b85">normalizeAndApplySavedTexCoords</a> ()</td></tr>
<tr class="separator:a157ddb6ce88f87553e45c04b79fa7b85"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6627d5e861d4c7d898b3e927b6ddc70e"><td class="memItemLeft" align="right" valign="top">vector&lt; <a class="el" href="of_constants_8h.html#ad4acc3774c730c65a67b4419154717d3">ofIndexType</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a6627d5e861d4c7d898b3e927b6ddc70e">getIndices</a> (int startIndex, int endIndex)</td></tr>
<tr class="separator:a6627d5e861d4c7d898b3e927b6ddc70e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pro_methods_classof_node"><td colspan="2" onclick="javascript:toggleInherit('pro_methods_classof_node')"><img src="closed.png" alt="-"/>&#160;Protected Member Functions inherited from <a class="el" href="classof_node.html">ofNode</a></td></tr>
<tr class="memitem:a7619a7cabd3690c782ad10cc13093074 inherit pro_methods_classof_node"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a7619a7cabd3690c782ad10cc13093074">createMatrix</a> ()</td></tr>
<tr class="separator:a7619a7cabd3690c782ad10cc13093074 inherit pro_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa31b92a732d3258f15c730ec8106273c inherit pro_methods_classof_node"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#aa31b92a732d3258f15c730ec8106273c">onPositionChanged</a> ()</td></tr>
<tr class="separator:aa31b92a732d3258f15c730ec8106273c inherit pro_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a423c1683913adf900cf8602b55361275 inherit pro_methods_classof_node"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a423c1683913adf900cf8602b55361275">onOrientationChanged</a> ()</td></tr>
<tr class="separator:a423c1683913adf900cf8602b55361275 inherit pro_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8e851ac0a96a9348d85e365e1e7c71be inherit pro_methods_classof_node"><td class="memItemLeft" align="right" valign="top">virtual void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a8e851ac0a96a9348d85e365e1e7c71be">onScaleChanged</a> ()</td></tr>
<tr class="separator:a8e851ac0a96a9348d85e365e1e7c71be inherit pro_methods_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr class="memitem:ae96f11ff257aa9491fbf689a1624770c"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_vec4f.html">ofVec4f</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#ae96f11ff257aa9491fbf689a1624770c">texCoords</a></td></tr>
<tr class="separator:ae96f11ff257aa9491fbf689a1624770c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aec45d7e4d1055f4374b9ee6d44de82ae"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#aec45d7e4d1055f4374b9ee6d44de82ae">usingVbo</a></td></tr>
<tr class="separator:aec45d7e4d1055f4374b9ee6d44de82ae"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a23397519eb4a50bd68660a1e9aba6cd4"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_ptr.html">ofPtr</a>&lt; <a class="el" href="classof_mesh.html">ofMesh</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a23397519eb4a50bd68660a1e9aba6cd4">mesh</a></td></tr>
<tr class="separator:a23397519eb4a50bd68660a1e9aba6cd4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5c61bfa24f27e827824d144bc4092e2a"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_mesh.html">ofMesh</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof3d_primitive.html#a5c61bfa24f27e827824d144bc4092e2a">normalsMesh</a></td></tr>
<tr class="separator:a5c61bfa24f27e827824d144bc4092e2a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pro_attribs_classof_node"><td colspan="2" onclick="javascript:toggleInherit('pro_attribs_classof_node')"><img src="closed.png" alt="-"/>&#160;Protected Attributes inherited from <a class="el" href="classof_node.html">ofNode</a></td></tr>
<tr class="memitem:a9fa60edff25434ada1671e837335fbdf inherit pro_attribs_classof_node"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classof_node.html">ofNode</a> *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classof_node.html#a9fa60edff25434ada1671e837335fbdf">parent</a></td></tr>
<tr class="separator:a9fa60edff25434ada1671e837335fbdf inherit pro_attribs_classof_node"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="af2f40819bcf5c442496dab452fa91eae"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">of3dPrimitive::of3dPrimitive </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="afff7a25964107e95f581b00ab8f83b98"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">of3dPrimitive::~of3dPrimitive </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a67735f4a20c6992f3ee1e95f023bfb02"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">of3dPrimitive::of3dPrimitive </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classof3d_primitive.html">of3dPrimitive</a> &amp;&#160;</td>
          <td class="paramname"><em>mom</em>)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="ab4b8f885982752b1ce14af3da8144ecc"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::clear </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a8f15788c4d116426957853a604fb9b6f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::disableColors </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a464b2f4f9b2132b395061aa44080b75b"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::disableNormals </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="ac13bb4ace465b00abec3fd9f73825121"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::disableTextures </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="aa8dd648110dd9cef3e14ce192d2b208e"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::draw </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="af9eb1d12247144a53e8031a54d5f0c19"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::draw </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="of_g_l_utils_8h.html#a6beb1fbbaba728909c78cda1eadfe28e">ofPolyRenderMode</a>&#160;</td>
          <td class="paramname"><em>renderType</em>)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a8827908140fd276554b65f6ab7bb4b77"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::drawAxes </td>
          <td>(</td>
          <td class="paramtype">float&#160;</td>
          <td class="paramname"><em>a_size</em>)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a3c6ed146402e3ac7dbc7a614086000b7"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::drawFaces </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="aa1eb38eb45d5b233f66814fd639d1752"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::drawNormals </td>
          <td>(</td>
          <td class="paramtype">float&#160;</td>
          <td class="paramname"><em>length</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>bFaceNormals</em> = <code>false</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a56bfd9c16069a94afcd1ff827dba5d06"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::drawVertices </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a7c85104c7efddb16ba7e07d4dcb1e85e"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::drawWireframe </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a328453a01022687422d1527414afc8b3"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::enableColors </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="ad4bb43ba66c67264d2a6298530ab20a7"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::enableNormals </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="aabe60b72a80f9bb01be030d0d17d9f85"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::enableTextures </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a6627d5e861d4c7d898b3e927b6ddc70e"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">vector&lt; <a class="el" href="of_constants_8h.html#ad4acc3774c730c65a67b4419154717d3">ofIndexType</a> &gt; of3dPrimitive::getIndices </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>startIndex</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>endIndex</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a83846bb15db870f7bca03b653e33ebd4"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classof_mesh.html">ofMesh</a> &amp; of3dPrimitive::getMesh </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a587142eae702b12669a369a8130bb3ad"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classof_mesh.html">ofMesh</a> * of3dPrimitive::getMeshPtr </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a646d09ddf195b48811ffada059f23ff7"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classof_vec4f.html">ofVec4f</a> &amp; of3dPrimitive::getTexCoords </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a65f754444368b9a7e3c96d7032106ff9"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classof_vec4f.html">ofVec4f</a> * of3dPrimitive::getTexCoordsPtr </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a396eb4253f091751efa9eb63d0885f66"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool of3dPrimitive::hasNormalsEnabled </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a20f8e5bc3113ec162d258b24379fca9c"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool of3dPrimitive::hasScaling </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="aa24eb5218bfaa8fcb605fc1362dfd4a4"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool of3dPrimitive::isUsingVbo </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="ad90951485c94c5c6c4e5dcd2e9051d9e"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::mapTexCoords </td>
          <td>(</td>
          <td class="paramtype">float&#160;</td>
          <td class="paramname"><em>u1</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">float&#160;</td>
          <td class="paramname"><em>v1</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">float&#160;</td>
          <td class="paramname"><em>u2</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">float&#160;</td>
          <td class="paramname"><em>v2</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a2ba2e23c9c13586cf7d7e2f29d193f1a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::mapTexCoordsFromTexture </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="classof_texture.html">ofTexture</a> &amp;&#160;</td>
          <td class="paramname"><em>inTexture</em>)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a157ddb6ce88f87553e45c04b79fa7b85"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::normalizeAndApplySavedTexCoords </td>
          <td>(</td>
          <td class="paramname">)</td><td></td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a190fc8fe46186cdb4bca8a4206046bfd"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classof3d_primitive.html">of3dPrimitive</a> &amp; of3dPrimitive::operator= </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classof3d_primitive.html">of3dPrimitive</a> &amp;&#160;</td>
          <td class="paramname"><em>mom</em>)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a0f570870b5d7e287570fe4ea0d29a3e2"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::removeMesh </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>index</em>)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a3d372c0c126f770b79e1e55e123ed4cd"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::removeTexture </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>index</em>)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="addbf2820728f1df687d800ec9fed706a"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void of3dPrimitive::setUseVbo </td>
          <td>(</td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>useVbo</em>)</td><td></td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a class="anchor" id="a23397519eb4a50bd68660a1e9aba6cd4"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classof_ptr.html">ofPtr</a>&lt;<a class="el" href="classof_mesh.html">ofMesh</a>&gt; of3dPrimitive::mesh</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="a5c61bfa24f27e827824d144bc4092e2a"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classof_mesh.html">ofMesh</a> of3dPrimitive::normalsMesh</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="ae96f11ff257aa9491fbf689a1624770c"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classof_vec4f.html">ofVec4f</a> of3dPrimitive::texCoords</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a class="anchor" id="aec45d7e4d1055f4374b9ee6d44de82ae"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">bool of3dPrimitive::usingVbo</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/home/arturo/Desktop/openFrameworks/libs/openFrameworks/3d/<a class="el" href="of3d_primitives_8h_source.html">of3dPrimitives.h</a></li>
<li>/home/arturo/Desktop/openFrameworks/libs/openFrameworks/3d/<a class="el" href="of3d_primitives_8cpp.html">of3dPrimitives.cpp</a></li>
</ul>
</div><!-- contents -->

            </div>
      </div>
      <div id="footer">
        ${self.footer()}
      </div> <!-- End Footer -->
    </div> <!-- End Content -->
  </body>
</html>
<%def name="header()">
  <%include file="header.mako" args="active='documentation'" />
</%def>
