<%inherit file="base.mako" />
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    ${self.head()}
    <meta http-equiv="X-UA-Compatible" content="IE=9"/>
    <meta name="generator" content="Doxygen 1.8.3.1"/>
    <title>openFrameworks: Class Index</title>
    <link href="tabs.css" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" src="dynsections.js"></script>
    <link href="search/search.css" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" src="search/search.js"></script>
    <script type="text/javascript">
      $(document).ready(function() { searchBox.OnSelectItem(0); });
    </script>
    <link href="doxygen.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div id="content">
      ${self.header()}
      <div id="body-wrap">
      		<div class="page-wide">
	            <div class="page-left-split">
           		    <h1 class="documentation">reference</h1> <ul class="docsadvanced"><li><a href="/documentation">basic</a></li> <li><a  class="active" href="/doxygen/annotated.html">advanced</a></li> </ul>
           		</div>
		        <div class="page-right-narrow">
			        <p>This documentation is automatically generated from the openFrameworks source code using doxygen and refers to the most recent release, version <strong>${bf.config.currentVersion}</strong>.</p>
		        </div>
       		</div>
      		<div class="page-wide">
      		    <div class="doxy-mainmenu">
<!-- Generated by Doxygen 1.8.4 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.html"><span>Related&#160;Pages</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.html"><span>Class&#160;List</span></a></li>
      <li><a href="classes.html"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.html"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.html"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="functions.html"><span>All</span></a></li>
      <li><a href="functions_func.html"><span>Functions</span></a></li>
      <li class="current"><a href="functions_vars.html"><span>Variables</span></a></li>
      <li><a href="functions_type.html"><span>Typedefs</span></a></li>
      <li><a href="functions_enum.html"><span>Enumerations</span></a></li>
      <li><a href="functions_eval.html"><span>Enumerator</span></a></li>
      <li><a href="functions_prop.html"><span>Properties</span></a></li>
      <li><a href="functions_rela.html"><span>Related&#160;Functions</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li class="current"><a href="functions_vars.html#index__"><span>_</span></a></li>
      <li><a href="functions_vars_0x61.html#index_a"><span>a</span></a></li>
      <li><a href="functions_vars_0x62.html#index_b"><span>b</span></a></li>
      <li><a href="functions_vars_0x63.html#index_c"><span>c</span></a></li>
      <li><a href="functions_vars_0x64.html#index_d"><span>d</span></a></li>
      <li><a href="functions_vars_0x65.html#index_e"><span>e</span></a></li>
      <li><a href="functions_vars_0x66.html#index_f"><span>f</span></a></li>
      <li><a href="functions_vars_0x67.html#index_g"><span>g</span></a></li>
      <li><a href="functions_vars_0x68.html#index_h"><span>h</span></a></li>
      <li><a href="functions_vars_0x69.html#index_i"><span>i</span></a></li>
      <li><a href="functions_vars_0x6b.html#index_k"><span>k</span></a></li>
      <li><a href="functions_vars_0x6c.html#index_l"><span>l</span></a></li>
      <li><a href="functions_vars_0x6d.html#index_m"><span>m</span></a></li>
      <li><a href="functions_vars_0x6e.html#index_n"><span>n</span></a></li>
      <li><a href="functions_vars_0x6f.html#index_o"><span>o</span></a></li>
      <li><a href="functions_vars_0x70.html#index_p"><span>p</span></a></li>
      <li><a href="functions_vars_0x71.html#index_q"><span>q</span></a></li>
      <li><a href="functions_vars_0x72.html#index_r"><span>r</span></a></li>
      <li><a href="functions_vars_0x73.html#index_s"><span>s</span></a></li>
      <li><a href="functions_vars_0x74.html#index_t"><span>t</span></a></li>
      <li><a href="functions_vars_0x75.html#index_u"><span>u</span></a></li>
      <li><a href="functions_vars_0x76.html#index_v"><span>v</span></a></li>
      <li><a href="functions_vars_0x77.html#index_w"><span>w</span></a></li>
      <li><a href="functions_vars_0x78.html#index_x"><span>x</span></a></li>
      <li><a href="functions_vars_0x79.html#index_y"><span>y</span></a></li>
      <li><a href="functions_vars_0x7a.html#index_z"><span>z</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div class="contents">
&#160;

<h3><a class="anchor" id="index__"></a>- _ -</h3><ul>
<li>_analogHistory
: <a class="el" href="classof_arduino.html#a2708f7ba1026d5ae57f1b7a9d4379a89">ofArduino</a>
</li>
<li>_analogHistoryLength
: <a class="el" href="classof_arduino.html#a0e24e6fc40ed254125dd3730b6bf0398">ofArduino</a>
</li>
<li>_analogPinReporting
: <a class="el" href="classof_arduino.html#ae5e8385829d3e33933a1e0cccf1b08b5">ofArduino</a>
</li>
<li>_digitalHistory
: <a class="el" href="classof_arduino.html#a4e7ebcce0f5ab825d6d320ffc180ffb7">ofArduino</a>
</li>
<li>_digitalHistoryLength
: <a class="el" href="classof_arduino.html#a30d75302eee4b8c20ca9ef342b59fd64">ofArduino</a>
</li>
<li>_digitalPinMode
: <a class="el" href="classof_arduino.html#a94a674555852d21edeb12353636af263">ofArduino</a>
</li>
<li>_digitalPinReporting
: <a class="el" href="classof_arduino.html#a5143efda2cea67a5441831b9b8ebbb38">ofArduino</a>
</li>
<li>_digitalPinValue
: <a class="el" href="classof_arduino.html#a4f5ff1ff907e90848aba58c24437b023">ofArduino</a>
</li>
<li>_digitalPortReporting
: <a class="el" href="classof_arduino.html#a10ff271e3a6e3561e8e073e06b7a5b40">ofArduino</a>
</li>
<li>_digitalPortValue
: <a class="el" href="classof_arduino.html#a171b9a3db49021e6b4b83962cb0d1dc6">ofArduino</a>
</li>
<li>_executeMultiByteCommand
: <a class="el" href="classof_arduino.html#a67ca5defa15c42c44b8bb435430bc76d">ofArduino</a>
</li>
<li>_firmwareName
: <a class="el" href="classof_arduino.html#a37b173a380744fae16fa9609b0d943d2">ofArduino</a>
</li>
<li>_firmwareVersionSum
: <a class="el" href="classof_arduino.html#af82008238cd1da0b9e9fdda5183c4b88">ofArduino</a>
</li>
<li>_initialized
: <a class="el" href="classof_arduino.html#aff9d0d6b6bd92143a205b1e770c805f5">ofArduino</a>
</li>
<li>_latestPixelFrame
: <a class="el" href="interface_q_t_kit_movie_renderer.html#a6e8e32c52e505614b387774d09e2499f">QTKitMovieRenderer</a>
</li>
<li>_latestTextureFrame
: <a class="el" href="interface_q_t_kit_movie_renderer.html#a63ec9a9563820c066d37b1b2ac9e75dd">QTKitMovieRenderer</a>
</li>
<li>_majorFirmwareVersion
: <a class="el" href="classof_arduino.html#ad1555a6578ba9fa5618d9fc8aea3ffc8">ofArduino</a>
</li>
<li>_majorProtocolVersion
: <a class="el" href="classof_arduino.html#a2e2485449cbf774fe8c1496364b7f5c9">ofArduino</a>
</li>
<li>_mat
: <a class="el" href="classof_matrix4x4.html#a28dd7ff5eee745c3ccd17e706fb7df54">ofMatrix4x4</a>
</li>
<li>_minorFirmwareVersion
: <a class="el" href="classof_arduino.html#a63529636712471e312fd8be056b62435">ofArduino</a>
</li>
<li>_minorProtocolVersion
: <a class="el" href="classof_arduino.html#a47da6901d68a4767436d0acaf3bcbba8">ofArduino</a>
</li>
<li>_movie
: <a class="el" href="interface_q_t_kit_movie_renderer.html#a035862eaa366c8a5febd5f45f10f0c16">QTKitMovieRenderer</a>
</li>
<li>_multiByteChannel
: <a class="el" href="classof_arduino.html#a1c273197e5668853062054e04c7c3a58">ofArduino</a>
</li>
<li>_mutex
: <a class="el" href="classof_delegate_3_01_t_obj_00_01void_00_01false_01_4.html#abc50ace2647e4d194cabbd7134952b01">ofDelegate&lt; TObj, void, false &gt;</a>
, <a class="el" href="classof_delegate.html#ae421e97d0d743d63a5c8151db39ddfdf">ofDelegate&lt; TObj, TArgs, useSender &gt;</a>
, <a class="el" href="classof_delegate_3_01_t_obj_00_01_t_args_00_01false_01_4.html#a489d77e597cbeeb84e7b345ad0f6509a">ofDelegate&lt; TObj, TArgs, false &gt;</a>
, <a class="el" href="classof_delegate_3_01_t_obj_00_01void_00_01true_01_4.html#a0aba3ebb4ebb8d4dfd46da9c9f106fe5">ofDelegate&lt; TObj, void, true &gt;</a>
</li>
<li>_port
: <a class="el" href="classof_arduino.html#ab492a5558cca3f440e9592bcbdde4609">ofArduino</a>
</li>
<li>_portStatus
: <a class="el" href="classof_arduino.html#a1998e90ce22b81c0a51a4199d34714a3">ofArduino</a>
</li>
<li>_receiverMethod
: <a class="el" href="classof_delegate_3_01_t_obj_00_01void_00_01true_01_4.html#a7f09d48a1fadd41e57cc85be6721c5cf">ofDelegate&lt; TObj, void, true &gt;</a>
, <a class="el" href="classof_delegate_3_01_t_obj_00_01void_00_01false_01_4.html#abef4066d3a20b9c0fa939b05d6ed2518">ofDelegate&lt; TObj, void, false &gt;</a>
, <a class="el" href="classof_delegate_3_01_t_obj_00_01_t_args_00_01false_01_4.html#a657b471e7def9c437fe942344fb060db">ofDelegate&lt; TObj, TArgs, false &gt;</a>
, <a class="el" href="classof_delegate.html#ab02b1b5b5fe31306c7a69c9db9d4d3a7">ofDelegate&lt; TObj, TArgs, useSender &gt;</a>
</li>
<li>_receiverObject
: <a class="el" href="classof_delegate_3_01_t_obj_00_01_t_args_00_01false_01_4.html#a87913990f98494f49f29d4a5e7695d15">ofDelegate&lt; TObj, TArgs, false &gt;</a>
, <a class="el" href="classof_delegate.html#ac653635506343fd5589b8491e33b479e">ofDelegate&lt; TObj, TArgs, useSender &gt;</a>
, <a class="el" href="classof_delegate_3_01_t_obj_00_01void_00_01true_01_4.html#a1ae6a9d1e90d2f57f1ea4eeb0fdb957f">ofDelegate&lt; TObj, void, true &gt;</a>
, <a class="el" href="classof_delegate_3_01_t_obj_00_01void_00_01false_01_4.html#a3725aa5e02a929c577c9c8782007bf95">ofDelegate&lt; TObj, void, false &gt;</a>
</li>
<li>_servoValue
: <a class="el" href="classof_arduino.html#a9e714f11a9cee3103dae053a3fec759f">ofArduino</a>
</li>
<li>_storedInputData
: <a class="el" href="classof_arduino.html#a93d5f4b065ec33d311421ae4dfb97a84">ofArduino</a>
</li>
<li>_stringHistory
: <a class="el" href="classof_arduino.html#abbbaa5177bc0d9db2f5f06b50153b30a">ofArduino</a>
</li>
<li>_stringHistoryLength
: <a class="el" href="classof_arduino.html#a313f9b3f0f7263d08939020a7b4506bc">ofArduino</a>
</li>
<li>_sysExData
: <a class="el" href="classof_arduino.html#aa5045c5647ba55fe2e5aa7fe86d4b123">ofArduino</a>
</li>
<li>_sysExHistory
: <a class="el" href="classof_arduino.html#adcd511519bf539e1239871f93e7a6766">ofArduino</a>
</li>
<li>_sysExHistoryLength
: <a class="el" href="classof_arduino.html#aed86ebecbd1ead7434900f9e5c97f5f2">ofArduino</a>
</li>
<li>_textureCache
: <a class="el" href="interface_q_t_kit_movie_renderer.html#af37410ac69cd13dc580862c64025768e">QTKitMovieRenderer</a>
</li>
<li>_totalDigitalPins
: <a class="el" href="classof_arduino.html#a27716e356068c7884ef407ce84d22b32">ofArduino</a>
</li>
<li>_v
: <a class="el" href="classof_quaternion.html#ab982b5638bed96d546f666393f4e2183">ofQuaternion</a>
</li>
<li>_visualContext
: <a class="el" href="interface_q_t_kit_movie_renderer.html#a60256236b82dfde9520c6678abc3217c">QTKitMovieRenderer</a>
</li>
<li>_waitForData
: <a class="el" href="classof_arduino.html#a4b3906ceec41536ef9dfa29926f4c31b">ofArduino</a>
</li>
</ul>
</div><!-- contents -->

            </div>
      </div>
      <div id="footer">
        ${self.footer()}
      </div> <!-- End Footer -->
    </div> <!-- End Content -->
  </body>
</html>
<%def name="header()">
  <%include file="header.mako" args="active='documentation'" />
</%def>
