<%inherit file="base.mako" />
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    ${self.head()}
    <meta http-equiv="X-UA-Compatible" content="IE=9"/>
    <meta name="generator" content="Doxygen 1.8.3.1"/>
    <title>openFrameworks: Class Index</title>
    <link href="tabs.css" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" src="dynsections.js"></script>
    <link href="search/search.css" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" src="search/search.js"></script>
    <script type="text/javascript">
      $(document).ready(function() { searchBox.OnSelectItem(0); });
    </script>
    <link href="doxygen.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div id="content">
      ${self.header()}
      <div id="body-wrap">
      		<div class="page-wide">
	            <div class="page-left-split">
           		    <h1 class="documentation">reference</h1> <ul class="docsadvanced"><li><a href="/documentation">basic</a></li> <li><a  class="active" href="/doxygen/annotated.html">advanced</a></li> </ul>
           		</div>
		        <div class="page-right-narrow">
			        <p>This documentation is automatically generated from the openFrameworks source code using doxygen and refers to the most recent release, version <strong>${bf.config.currentVersion}</strong>.</p>
		        </div>
       		</div>
      		<div class="page-wide">
      		    <div class="doxy-mainmenu">
<!-- Generated by Doxygen 1.8.4 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.html"><span>Related&#160;Pages</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li><a href="annotated.html"><span>Classes</span></a></li>
      <li class="current"><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.html"><span>File&#160;List</span></a></li>
      <li><a href="globals.html"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_84d5b34cee6369a03c8d1f3b970ed216.html">openFrameworks</a></li><li class="navelem"><a class="el" href="dir_71ce5ed87e0eac5aae2f3eaf44c16fe2.html">graphics</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">ofCairoRenderer.h</div>  </div>
</div><!--header-->
<div class="contents">
<a href="of_cairo_renderer_8h.html">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;<span class="preprocessor">#pragma once</span></div>
<div class="line"><a name="l00002"></a><span class="lineno">    2</span>&#160;<span class="preprocessor"></span></div>
<div class="line"><a name="l00003"></a><span class="lineno">    3</span>&#160;</div>
<div class="line"><a name="l00004"></a><span class="lineno">    4</span>&#160;<span class="preprocessor">#include &quot;cairo-features.h&quot;</span></div>
<div class="line"><a name="l00005"></a><span class="lineno">    5</span>&#160;<span class="preprocessor">#include &quot;cairo-pdf.h&quot;</span></div>
<div class="line"><a name="l00006"></a><span class="lineno">    6</span>&#160;<span class="preprocessor">#include &quot;cairo-svg.h&quot;</span></div>
<div class="line"><a name="l00007"></a><span class="lineno">    7</span>&#160;<span class="preprocessor">#include &quot;cairo.h&quot;</span></div>
<div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;<span class="preprocessor">#include &lt;deque&gt;</span></div>
<div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;<span class="preprocessor">#include &lt;stack&gt;</span></div>
<div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="of_matrix4x4_8h.html">ofMatrix4x4.h</a>&quot;</span></div>
<div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="of_base_types_8h.html">ofBaseTypes.h</a>&quot;</span></div>
<div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="of_path_8h.html">ofPath.h</a>&quot;</span></div>
<div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;</div>
<div class="line"><a name="l00014"></a><span class="lineno"><a class="code" href="classof_cairo_renderer.html">   14</a></span>&#160;<span class="keyword">class </span><a class="code" href="classof_cairo_renderer.html">ofCairoRenderer</a>: <span class="keyword">public</span> <a class="code" href="classof_base_renderer.html">ofBaseRenderer</a>{</div>
<div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="keyword">public</span>:</div>
<div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;    <a class="code" href="classof_cairo_renderer.html#ad079c5691b32f860b4c2fb8875c9ebe2">ofCairoRenderer</a>();</div>
<div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;    <a class="code" href="classof_cairo_renderer.html#a3e6a6b041771a84b52dee3bf7599854e">~ofCairoRenderer</a>();</div>
<div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;</div>
<div class="line"><a name="l00019"></a><span class="lineno"><a class="code" href="classof_cairo_renderer.html#a91646f95cafb8c580de77a151a19081a">   19</a></span>&#160;    <span class="keyword">static</span> <span class="keyword">const</span> <span class="keywordtype">string</span> <a class="code" href="classof_cairo_renderer.html#a91646f95cafb8c580de77a151a19081a">TYPE</a>;</div>
<div class="line"><a name="l00020"></a><span class="lineno"><a class="code" href="classof_cairo_renderer.html#a069ceb0e7e8566f9aeca00f94bf6c66b">   20</a></span>&#160;    <span class="keyword">const</span> <span class="keywordtype">string</span> &amp; <a class="code" href="classof_cairo_renderer.html#a069ceb0e7e8566f9aeca00f94bf6c66b">getType</a>(){ <span class="keywordflow">return</span> <a class="code" href="classof_cairo_renderer.html#a91646f95cafb8c580de77a151a19081a">TYPE</a>; }</div>
<div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;</div>
<div class="line"><a name="l00022"></a><span class="lineno"><a class="code" href="classof_cairo_renderer.html#aa4f542abccc80b9288466943a947ac55">   22</a></span>&#160;    <span class="keyword">enum</span> <a class="code" href="classof_cairo_renderer.html#aa4f542abccc80b9288466943a947ac55">Type</a>{</div>
<div class="line"><a name="l00023"></a><span class="lineno"><a class="code" href="classof_cairo_renderer.html#aa4f542abccc80b9288466943a947ac55a57b815b8dd08e819b826cade2455413b">   23</a></span>&#160;        <a class="code" href="classof_cairo_renderer.html#aa4f542abccc80b9288466943a947ac55a57b815b8dd08e819b826cade2455413b">PDF</a>,</div>
<div class="line"><a name="l00024"></a><span class="lineno"><a class="code" href="classof_cairo_renderer.html#aa4f542abccc80b9288466943a947ac55a1126079de0933bf6636da2cbe8eeb123">   24</a></span>&#160;        <a class="code" href="classof_cairo_renderer.html#aa4f542abccc80b9288466943a947ac55a1126079de0933bf6636da2cbe8eeb123">SVG</a>,</div>
<div class="line"><a name="l00025"></a><span class="lineno"><a class="code" href="classof_cairo_renderer.html#aa4f542abccc80b9288466943a947ac55a8f71ff4f9145e0d1e4f94bb7b0a302ad">   25</a></span>&#160;        <a class="code" href="classof_cairo_renderer.html#aa4f542abccc80b9288466943a947ac55a8f71ff4f9145e0d1e4f94bb7b0a302ad">IMAGE</a>,</div>
<div class="line"><a name="l00026"></a><span class="lineno"><a class="code" href="classof_cairo_renderer.html#aa4f542abccc80b9288466943a947ac55ad223e1e16cd4dce5d2c403d020d5f501">   26</a></span>&#160;        <a class="code" href="classof_cairo_renderer.html#aa4f542abccc80b9288466943a947ac55ad223e1e16cd4dce5d2c403d020d5f501">FROM_FILE_EXTENSION</a></div>
<div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;    };</div>
<div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a3ccf5482431574783cdecc8e1110ec44">setup</a>(<span class="keywordtype">string</span> filename, <a class="code" href="classof_cairo_renderer.html#aa4f542abccc80b9288466943a947ac55">Type</a> type=<a class="code" href="classof_cairo_renderer.html#aa4f542abccc80b9288466943a947ac55ad223e1e16cd4dce5d2c403d020d5f501">ofCairoRenderer::FROM_FILE_EXTENSION</a>, <span class="keywordtype">bool</span> multiPage=<span class="keyword">true</span>, <span class="keywordtype">bool</span> b3D=<span class="keyword">false</span>, <a class="code" href="classof_rectangle.html" title="A class representing a 2D rectangle. ">ofRectangle</a> <a class="code" href="classof_cairo_renderer.html#aeb4bdbd4882a0846cdd95d4a17c981a3">viewport</a> = <a class="code" href="classof_rectangle.html" title="A class representing a 2D rectangle. ">ofRectangle</a>(0,0,0,0));</div>
<div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a7823ed5070209eefa4cd682a280c4f5a">setupMemoryOnly</a>(<a class="code" href="classof_cairo_renderer.html#aa4f542abccc80b9288466943a947ac55">Type</a> _type, <span class="keywordtype">bool</span> multiPage=<span class="keyword">true</span>, <span class="keywordtype">bool</span> b3D=<span class="keyword">false</span>, <a class="code" href="classof_rectangle.html" title="A class representing a 2D rectangle. ">ofRectangle</a> <a class="code" href="classof_cairo_renderer.html#aeb4bdbd4882a0846cdd95d4a17c981a3">viewport</a> = <a class="code" href="classof_rectangle.html" title="A class representing a 2D rectangle. ">ofRectangle</a>(0,0,0,0));</div>
<div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a8280b52ecf27721b8d33ac8652b4bb65">close</a>();</div>
<div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a1d62dcba797ad990dad64b1fd0dc7743">flush</a>();</div>
<div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;</div>
<div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a57f44289cb55fb1c6601b456f1c06f06">update</a>();</div>
<div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;</div>
<div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a7b07626fdbc8410889ee9884ce471fa0">draw</a>(<a class="code" href="classof_path.html">ofPath</a> &amp; shape);</div>
<div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a7b07626fdbc8410889ee9884ce471fa0">draw</a>(<a class="code" href="structof_path_1_1_command.html">ofPath::Command</a> &amp; path);</div>
<div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a7b07626fdbc8410889ee9884ce471fa0">draw</a>(<a class="code" href="classof_polyline.html">ofPolyline</a> &amp; poly);</div>
<div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a7b07626fdbc8410889ee9884ce471fa0">draw</a>(<a class="code" href="classof_mesh.html">ofMesh</a> &amp; vertexData, <span class="keywordtype">bool</span> useColors=<span class="keyword">true</span>, <span class="keywordtype">bool</span> useTextures=<span class="keyword">true</span>, <span class="keywordtype">bool</span> useNormals=<span class="keyword">true</span>);</div>
<div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a7b07626fdbc8410889ee9884ce471fa0">draw</a>(<a class="code" href="classof_mesh.html">ofMesh</a> &amp; vertexData, <a class="code" href="of_g_l_utils_8h.html#a6beb1fbbaba728909c78cda1eadfe28e">ofPolyRenderMode</a> mode, <span class="keywordtype">bool</span> useColors = <span class="keyword">false</span>, <span class="keywordtype">bool</span> useTextures = <span class="keyword">false</span>, <span class="keywordtype">bool</span> useNormals = <span class="keyword">false</span>);</div>
<div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a7b07626fdbc8410889ee9884ce471fa0">draw</a>(<a class="code" href="classof3d_primitive.html">of3dPrimitive</a>&amp; model, <a class="code" href="of_g_l_utils_8h.html#a6beb1fbbaba728909c78cda1eadfe28e">ofPolyRenderMode</a> renderType );</div>
<div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a7b07626fdbc8410889ee9884ce471fa0">draw</a>(vector&lt;ofPoint&gt; &amp; vertexData, <a class="code" href="of_g_l_utils_8h.html#a0f71f0b23a18629a446952d5540e16e0">ofPrimitiveMode</a> drawMode);</div>
<div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a7b07626fdbc8410889ee9884ce471fa0">draw</a>(<a class="code" href="classof_image__.html">ofImage</a> &amp; img, <span class="keywordtype">float</span> x, <span class="keywordtype">float</span> y, <span class="keywordtype">float</span> z, <span class="keywordtype">float</span> w, <span class="keywordtype">float</span> h, <span class="keywordtype">float</span> sx, <span class="keywordtype">float</span> sy, <span class="keywordtype">float</span> sw, <span class="keywordtype">float</span> sh);</div>
<div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a7b07626fdbc8410889ee9884ce471fa0">draw</a>(<a class="code" href="classof_image__.html" title="A class representing an image using memory and gpu based pixels. ">ofFloatImage</a> &amp; image, <span class="keywordtype">float</span> x, <span class="keywordtype">float</span> y, <span class="keywordtype">float</span> z, <span class="keywordtype">float</span> w, <span class="keywordtype">float</span> h, <span class="keywordtype">float</span> sx, <span class="keywordtype">float</span> sy, <span class="keywordtype">float</span> sw, <span class="keywordtype">float</span> sh);</div>
<div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a7b07626fdbc8410889ee9884ce471fa0">draw</a>(<a class="code" href="classof_image__.html" title="A class representing an image using memory and gpu based pixels. ">ofShortImage</a> &amp; image, <span class="keywordtype">float</span> x, <span class="keywordtype">float</span> y, <span class="keywordtype">float</span> z, <span class="keywordtype">float</span> w, <span class="keywordtype">float</span> h, <span class="keywordtype">float</span> sx, <span class="keywordtype">float</span> sy, <span class="keywordtype">float</span> sw, <span class="keywordtype">float</span> sh);</div>
<div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;</div>
<div class="line"><a name="l00046"></a><span class="lineno"><a class="code" href="classof_cairo_renderer.html#a933632be24a7f9ee8175c3660a263c24">   46</a></span>&#160;    <span class="keywordtype">bool</span> <a class="code" href="classof_cairo_renderer.html#a933632be24a7f9ee8175c3660a263c24">rendersPathPrimitives</a>(){</div>
<div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;        <span class="keywordflow">return</span> <span class="keyword">true</span>;</div>
<div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;    }</div>
<div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;</div>
<div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;    <span class="comment">//--------------------------------------------</span></div>
<div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;    <span class="comment">// transformations</span></div>
<div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#acf52b56ca3516c61f81ccc08cfadced1">pushView</a>();</div>
<div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a95e3b1bf17c56b334ae9b265d0caf971">popView</a>();</div>
<div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;</div>
<div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;    <span class="comment">// setup matrices and viewport (upto you to push and pop view before and after)</span></div>
<div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;    <span class="comment">// if width or height are 0, assume windows dimensions (ofGetWidth(), ofGetHeight())</span></div>
<div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;    <span class="comment">// if nearDist or farDist are 0 assume defaults (calculated based on width / height)</span></div>
<div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#aeb4bdbd4882a0846cdd95d4a17c981a3">viewport</a>(<a class="code" href="classof_rectangle.html" title="A class representing a 2D rectangle. ">ofRectangle</a> <a class="code" href="classof_cairo_renderer.html#aeb4bdbd4882a0846cdd95d4a17c981a3">viewport</a>);</div>
<div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#aeb4bdbd4882a0846cdd95d4a17c981a3">viewport</a>(<span class="keywordtype">float</span> x = 0, <span class="keywordtype">float</span> y = 0, <span class="keywordtype">float</span> <a class="code" href="of_app_e_g_l_window_8cpp.html#aca34d28e3d8bcbcadb8edb4e3af24f8c">width</a> = 0, <span class="keywordtype">float</span> <a class="code" href="of_app_e_g_l_window_8cpp.html#ab2e78c61905b4419fcc7b4cfc500fe85">height</a> = 0, <span class="keywordtype">bool</span> invertY = <span class="keyword">true</span>);</div>
<div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#afe9b17e8a0585eae43cb00c6c9996c12">setupScreenPerspective</a>(<span class="keywordtype">float</span> <a class="code" href="of_app_e_g_l_window_8cpp.html#aca34d28e3d8bcbcadb8edb4e3af24f8c">width</a> = 0, <span class="keywordtype">float</span> <a class="code" href="of_app_e_g_l_window_8cpp.html#ab2e78c61905b4419fcc7b4cfc500fe85">height</a> = 0, <span class="keywordtype">float</span> fov = 60, <span class="keywordtype">float</span> nearDist = 0, <span class="keywordtype">float</span> farDist = 0);</div>
<div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a573712d889284c0b84765dbeb0ba2785">setupScreenOrtho</a>(<span class="keywordtype">float</span> <a class="code" href="of_app_e_g_l_window_8cpp.html#aca34d28e3d8bcbcadb8edb4e3af24f8c">width</a> = 0, <span class="keywordtype">float</span> <a class="code" href="of_app_e_g_l_window_8cpp.html#ab2e78c61905b4419fcc7b4cfc500fe85">height</a> = 0, <span class="keywordtype">float</span> nearDist = -1, <span class="keywordtype">float</span> farDist = 1);</div>
<div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;    <a class="code" href="classof_rectangle.html" title="A class representing a 2D rectangle. ">ofRectangle</a> <a class="code" href="classof_cairo_renderer.html#a34b2cf0594a8e0eb0a0e646ac2042ec7">getCurrentViewport</a>();</div>
<div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;    <span class="keywordtype">int</span> <a class="code" href="classof_cairo_renderer.html#a888924ffc3a037f67eb67dd3d4641329">getViewportWidth</a>();</div>
<div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;    <span class="keywordtype">int</span> <a class="code" href="classof_cairo_renderer.html#ac1f2e3922892ab6c6dd4482f1a259ff4">getViewportHeight</a>();</div>
<div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;</div>
<div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a97610b9999e6e5831d88ff65926eeb33">setCoordHandedness</a>(<a class="code" href="of_constants_8h.html#a35cd63b4a2e112ecf30eaf0542f2388b">ofHandednessType</a> handedness);</div>
<div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;    <a class="code" href="of_constants_8h.html#a35cd63b4a2e112ecf30eaf0542f2388b">ofHandednessType</a> <a class="code" href="classof_cairo_renderer.html#ad4dfd1712d8a302c4191fcd0c5ede706">getCoordHandedness</a>();</div>
<div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;</div>
<div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;    <span class="comment">// drawing modes</span></div>
<div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a0b4c7064a42559a09763c60489c9ee37">setRectMode</a>(<a class="code" href="of_constants_8h.html#a52116548570a64993cbe3be944443fce">ofRectMode</a> mode);</div>
<div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;    <a class="code" href="of_constants_8h.html#a52116548570a64993cbe3be944443fce">ofRectMode</a> <a class="code" href="classof_cairo_renderer.html#ad53c213918dd9a3011788ac36ed21f28">getRectMode</a>();</div>
<div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a535bf1e13b51d0a5d4de152a94382c15">setFillMode</a>(<a class="code" href="of_constants_8h.html#ae2388165eb5c77ed1edbee0d7d68d4dc">ofFillFlag</a> fill);</div>
<div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;    <a class="code" href="of_constants_8h.html#ae2388165eb5c77ed1edbee0d7d68d4dc">ofFillFlag</a> <a class="code" href="classof_cairo_renderer.html#a2e3ec897cb1c67bce8e99900c50cc8af">getFillMode</a>();</div>
<div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#aa23662a69a84b60b645b0b732eb69796">setLineWidth</a>(<span class="keywordtype">float</span> lineWidth);</div>
<div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#ac8fc19498897ad69011ee7db5420558f">setDepthTest</a>(<span class="keywordtype">bool</span> depthTest);</div>
<div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#ad17ae254ba8de9f79708149a78fc26eb">setBlendMode</a>(<a class="code" href="of_constants_8h.html#a5f194ae56b1bc61651eac7184ed1ad2e">ofBlendMode</a> blendMode);</div>
<div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a1901f46679555e72239d24807a269081">setLineSmoothing</a>(<span class="keywordtype">bool</span> smooth);</div>
<div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a32514b1bf58a003af06a2cab45fe592f">setSphereResolution</a>(<span class="keywordtype">int</span> res);</div>
<div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a7c74b7dba42387e54164b32f9edcbe41">enableAntiAliasing</a>();</div>
<div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a8532f4c77724902b2ccfc1a5c4932d85">disableAntiAliasing</a>();</div>
<div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;</div>
<div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;    <span class="comment">//our openGL wrappers</span></div>
<div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#ae80318ec09fad18566517d1034fa7bec">pushMatrix</a>();</div>
<div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a14b22e5b97713bd80adc129923a33fbe">popMatrix</a>();</div>
<div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;    <a class="code" href="classof_matrix4x4.html">ofMatrix4x4</a> <a class="code" href="classof_cairo_renderer.html#a8661b597a453c632072b35781a6cf0d3">getCurrentMatrix</a>(<a class="code" href="of_constants_8h.html#a2d00334d4ec22117e5bfcafb5570263d">ofMatrixMode</a> matrixMode_) <span class="keyword">const</span>;</div>
<div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#ac7767ad5bc65fe42932d8043ffccd699">translate</a>(<span class="keywordtype">float</span> x, <span class="keywordtype">float</span> y, <span class="keywordtype">float</span> z = 0);</div>
<div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#ac7767ad5bc65fe42932d8043ffccd699">translate</a>(<span class="keyword">const</span> <a class="code" href="classof_vec3f.html">ofPoint</a> &amp; p);</div>
<div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a02195750c37c906936670424102c2cf4">scale</a>(<span class="keywordtype">float</span> xAmnt, <span class="keywordtype">float</span> yAmnt, <span class="keywordtype">float</span> zAmnt = 1);</div>
<div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a8822b11dafbe4649824e1abaa2d90377">rotate</a>(<span class="keywordtype">float</span> degrees, <span class="keywordtype">float</span> vecX, <span class="keywordtype">float</span> vecY, <span class="keywordtype">float</span> vecZ);</div>
<div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a95e2617b09a278951a9da61b84dd73f4">rotateX</a>(<span class="keywordtype">float</span> degrees);</div>
<div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a8708e85a264993c6a1c17a603f5c3622">rotateY</a>(<span class="keywordtype">float</span> degrees);</div>
<div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#ae49c0dd54cc8eeededda39ce57df3958">rotateZ</a>(<span class="keywordtype">float</span> degrees);</div>
<div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a8822b11dafbe4649824e1abaa2d90377">rotate</a>(<span class="keywordtype">float</span> degrees);</div>
<div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a315d7ce4683c7f914d3f9eaae7e49714">matrixMode</a>(<a class="code" href="of_constants_8h.html#a2d00334d4ec22117e5bfcafb5570263d">ofMatrixMode</a> mode);</div>
<div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#adebe606824f8a55acfb755590e8de7ff">loadIdentityMatrix</a> (<span class="keywordtype">void</span>);</div>
<div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a12e2466567bf1e322f09ef5bdf6c07e2">loadMatrix</a> (<span class="keyword">const</span> <a class="code" href="classof_matrix4x4.html">ofMatrix4x4</a> &amp; m);</div>
<div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a12e2466567bf1e322f09ef5bdf6c07e2">loadMatrix</a> (<span class="keyword">const</span> <span class="keywordtype">float</span> * m);</div>
<div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a21933eedef7fe07dce06776cedeb6100">multMatrix</a> (<span class="keyword">const</span> <a class="code" href="classof_matrix4x4.html">ofMatrix4x4</a> &amp; m);</div>
<div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a21933eedef7fe07dce06776cedeb6100">multMatrix</a> (<span class="keyword">const</span> <span class="keywordtype">float</span> * m);</div>
<div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;</div>
<div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;    <span class="comment">// screen coordinate things / default gl values</span></div>
<div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a067de4b242130b80d9e07617eda7dd37">setupGraphicDefaults</a>();</div>
<div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#aff0476945a318bc4580e639b60017338">setupScreen</a>();</div>
<div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;</div>
<div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;    <span class="comment">// color options</span></div>
<div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#aae49df33ec0e2e50b192d02bc9254329">setColor</a>(<span class="keywordtype">int</span> r, <span class="keywordtype">int</span> g, <span class="keywordtype">int</span> b); <span class="comment">// 0-255</span></div>
<div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#aae49df33ec0e2e50b192d02bc9254329">setColor</a>(<span class="keywordtype">int</span> r, <span class="keywordtype">int</span> g, <span class="keywordtype">int</span> b, <span class="keywordtype">int</span> a); <span class="comment">// 0-255</span></div>
<div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#aae49df33ec0e2e50b192d02bc9254329">setColor</a>(<span class="keyword">const</span> <a class="code" href="classof_color__.html">ofColor</a> &amp; color);</div>
<div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#aae49df33ec0e2e50b192d02bc9254329">setColor</a>(<span class="keyword">const</span> <a class="code" href="classof_color__.html">ofColor</a> &amp; color, <span class="keywordtype">int</span> _a);</div>
<div class="line"><a name="l00110"></a><span class="lineno">  110</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#aae49df33ec0e2e50b192d02bc9254329">setColor</a>(<span class="keywordtype">int</span> gray); <span class="comment">// new set a color as grayscale with one argument</span></div>
<div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a12eb0672c7053617129837077700fbe4">setHexColor</a>( <span class="keywordtype">int</span> hexColor ); <span class="comment">// hex, like web 0xFF0033;</span></div>
<div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;</div>
<div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;    <span class="comment">// bg color</span></div>
<div class="line"><a name="l00114"></a><span class="lineno">  114</span>&#160;    <a class="code" href="classof_color__.html">ofFloatColor</a> &amp; <a class="code" href="classof_cairo_renderer.html#a2abf80732d95985707631620284b547b">getBgColor</a>();</div>
<div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;    <span class="keywordtype">bool</span> <a class="code" href="classof_cairo_renderer.html#adbd43a9920495d686c9381e44c723c68">bClearBg</a>();</div>
<div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#afe6b29f670e797e1cab85562ae365372">background</a>(<span class="keyword">const</span> <a class="code" href="classof_color__.html">ofColor</a> &amp; c);</div>
<div class="line"><a name="l00117"></a><span class="lineno">  117</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#afe6b29f670e797e1cab85562ae365372">background</a>(<span class="keywordtype">float</span> brightness);</div>
<div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#afe6b29f670e797e1cab85562ae365372">background</a>(<span class="keywordtype">int</span> hexColor, <span class="keywordtype">float</span> _a=255.0f);</div>
<div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#afe6b29f670e797e1cab85562ae365372">background</a>(<span class="keywordtype">int</span> r, <span class="keywordtype">int</span> g, <span class="keywordtype">int</span> b, <span class="keywordtype">int</span> a=255);</div>
<div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;</div>
<div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a3c095b39a1fa8f7af272331c88a559c0">setBackgroundAuto</a>(<span class="keywordtype">bool</span> bManual);       <span class="comment">// default is true</span></div>
<div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;</div>
<div class="line"><a name="l00123"></a><span class="lineno">  123</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a08f08fcdb8864fde81872d1f3b2308c9">clear</a>(<span class="keywordtype">float</span> r, <span class="keywordtype">float</span> g, <span class="keywordtype">float</span> b, <span class="keywordtype">float</span> a=0);</div>
<div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a08f08fcdb8864fde81872d1f3b2308c9">clear</a>(<span class="keywordtype">float</span> brightness, <span class="keywordtype">float</span> a=0);</div>
<div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#ad3a309e756af77fa962928018e1caeee">clearAlpha</a>();</div>
<div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;</div>
<div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;    <span class="comment">// drawing</span></div>
<div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#af8f5534e273d3e480e983e49cb25416b">drawLine</a>(<span class="keywordtype">float</span> x1, <span class="keywordtype">float</span> y1, <span class="keywordtype">float</span> z1, <span class="keywordtype">float</span> x2, <span class="keywordtype">float</span> y2, <span class="keywordtype">float</span> z2);</div>
<div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a87ca38cd07aad94f36d3bc0aa9bab757">drawRectangle</a>(<span class="keywordtype">float</span> x, <span class="keywordtype">float</span> y, <span class="keywordtype">float</span> z, <span class="keywordtype">float</span> w, <span class="keywordtype">float</span> h);</div>
<div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a7437fda0cc3291a4734c30d5215cb304">drawTriangle</a>(<span class="keywordtype">float</span> x1, <span class="keywordtype">float</span> y1, <span class="keywordtype">float</span> z1, <span class="keywordtype">float</span> x2, <span class="keywordtype">float</span> y2, <span class="keywordtype">float</span> z2, <span class="keywordtype">float</span> x3, <span class="keywordtype">float</span> y3, <span class="keywordtype">float</span> z3);</div>
<div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a92e52d81d4aee42ee2444a82bf85d748">drawCircle</a>(<span class="keywordtype">float</span> x, <span class="keywordtype">float</span> y, <span class="keywordtype">float</span> z, <span class="keywordtype">float</span> radius);</div>
<div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a70ee8a6229af5c0dfe30b241a83f3480">drawSphere</a>(<span class="keywordtype">float</span> x, <span class="keywordtype">float</span> y, <span class="keywordtype">float</span> z, <span class="keywordtype">float</span> radius);</div>
<div class="line"><a name="l00133"></a><span class="lineno">  133</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a8641b0baf1a323a1371a025ecc844eb5">drawEllipse</a>(<span class="keywordtype">float</span> x, <span class="keywordtype">float</span> y, <span class="keywordtype">float</span> z, <span class="keywordtype">float</span> <a class="code" href="of_app_e_g_l_window_8cpp.html#aca34d28e3d8bcbcadb8edb4e3af24f8c">width</a>, <span class="keywordtype">float</span> <a class="code" href="of_app_e_g_l_window_8cpp.html#ab2e78c61905b4419fcc7b4cfc500fe85">height</a>);</div>
<div class="line"><a name="l00134"></a><span class="lineno">  134</span>&#160;    <span class="keywordtype">void</span> <a class="code" href="classof_cairo_renderer.html#a686cd4854a5e1fb94a16386728d6c695">drawString</a>(<span class="keywordtype">string</span> text, <span class="keywordtype">float</span> x, <span class="keywordtype">float</span> y, <span class="keywordtype">float</span> z, <a class="code" href="of_constants_8h.html#a14966be842b99f71080a7444cebbc0b7">ofDrawBitmapMode</a> mode);</div>
<div class="line"><a name="l00135"></a><span class="lineno">  135</span>&#160;</div>
<div class="line"><a name="l00136"></a><span class="lineno">  136</span>&#160;    <span class="comment">// cairo specifics</span></div>
<div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;    cairo_t * <a class="code" href="classof_cairo_renderer.html#ac35a58c7b9f691b3e0f77851ffccd9b0">getCairoContext</a>();</div>
<div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;    cairo_surface_t * <a class="code" href="classof_cairo_renderer.html#aa7eb68c44314f33c1b4e2b99fe52c242">getCairoSurface</a>();</div>
<div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;    <a class="code" href="classof_pixels__.html">ofPixels</a> &amp; <a class="code" href="classof_cairo_renderer.html#a39ec92620dcfe15010c95e118e6d97a0">getImageSurfacePixels</a>();</div>
<div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;    <a class="code" href="classof_buffer.html">ofBuffer</a> &amp; <a class="code" href="classof_cairo_renderer.html#a138eb08ac625f4d01da957ea5275b7c4">getContentBuffer</a>();</div>
<div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;</div>
<div class="line"><a name="l00142"></a><span class="lineno">  142</span>&#160;<span class="keyword">private</span>:</div>
<div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;    <span class="keywordtype">void</span> setStyle(<span class="keyword">const</span> <a class="code" href="classof_style.html">ofStyle</a> &amp; style);</div>
<div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;    cairo_matrix_t * getCairoMatrix();</div>
<div class="line"><a name="l00145"></a><span class="lineno">  145</span>&#160;    <span class="keywordtype">void</span> setCairoMatrix();</div>
<div class="line"><a name="l00146"></a><span class="lineno">  146</span>&#160;    <a class="code" href="classof_vec3f.html">ofVec3f</a> transform(<a class="code" href="classof_vec3f.html">ofVec3f</a> vec);</div>
<div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;    <span class="keyword">static</span> _cairo_status stream_function(<span class="keywordtype">void</span> *closure,<span class="keyword">const</span> <span class="keywordtype">unsigned</span> <span class="keywordtype">char</span> *data, <span class="keywordtype">unsigned</span> <span class="keywordtype">int</span> length);</div>
<div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;</div>
<div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160;    deque&lt;ofPoint&gt; curvePoints;</div>
<div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160;    cairo_t * cr;</div>
<div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;    cairo_surface_t * surface;</div>
<div class="line"><a name="l00152"></a><span class="lineno">  152</span>&#160;    <span class="keywordtype">bool</span> bBackgroundAuto;</div>
<div class="line"><a name="l00153"></a><span class="lineno">  153</span>&#160;    <a class="code" href="classof_color__.html">ofFloatColor</a> bgColor;</div>
<div class="line"><a name="l00154"></a><span class="lineno">  154</span>&#160;</div>
<div class="line"><a name="l00155"></a><span class="lineno">  155</span>&#160;    stack&lt;cairo_matrix_t&gt; matrixStack;</div>
<div class="line"><a name="l00156"></a><span class="lineno">  156</span>&#160;    cairo_matrix_t tmpMatrix;</div>
<div class="line"><a name="l00157"></a><span class="lineno">  157</span>&#160;</div>
<div class="line"><a name="l00158"></a><span class="lineno">  158</span>&#160;    <a class="code" href="classof_cairo_renderer.html#aa4f542abccc80b9288466943a947ac55">Type</a> type;</div>
<div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;    <span class="keywordtype">int</span> page;</div>
<div class="line"><a name="l00160"></a><span class="lineno">  160</span>&#160;    <span class="keywordtype">bool</span> multiPage;</div>
<div class="line"><a name="l00161"></a><span class="lineno">  161</span>&#160;</div>
<div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160;    <span class="comment">// 3d transformation</span></div>
<div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160;    <span class="keywordtype">bool</span> b3D;</div>
<div class="line"><a name="l00164"></a><span class="lineno">  164</span>&#160;    <a class="code" href="classof_matrix4x4.html">ofMatrix4x4</a> projection;</div>
<div class="line"><a name="l00165"></a><span class="lineno">  165</span>&#160;    <a class="code" href="classof_matrix4x4.html">ofMatrix4x4</a> modelView;</div>
<div class="line"><a name="l00166"></a><span class="lineno">  166</span>&#160;    <a class="code" href="classof_rectangle.html" title="A class representing a 2D rectangle. ">ofRectangle</a> viewportRect;</div>
<div class="line"><a name="l00167"></a><span class="lineno">  167</span>&#160;</div>
<div class="line"><a name="l00168"></a><span class="lineno">  168</span>&#160;    stack&lt;ofMatrix4x4&gt; projectionStack;</div>
<div class="line"><a name="l00169"></a><span class="lineno">  169</span>&#160;    stack&lt;ofMatrix4x4&gt; modelViewStack;</div>
<div class="line"><a name="l00170"></a><span class="lineno">  170</span>&#160;    stack&lt;ofRectangle&gt; viewportStack;</div>
<div class="line"><a name="l00171"></a><span class="lineno">  171</span>&#160;    </div>
<div class="line"><a name="l00172"></a><span class="lineno">  172</span>&#160;    <a class="code" href="of_constants_8h.html#a2d00334d4ec22117e5bfcafb5570263d">ofMatrixMode</a> currentMatrixMode;</div>
<div class="line"><a name="l00173"></a><span class="lineno">  173</span>&#160;</div>
<div class="line"><a name="l00174"></a><span class="lineno">  174</span>&#160;    vector&lt;ofPoint&gt; sphereVerts;</div>
<div class="line"><a name="l00175"></a><span class="lineno">  175</span>&#160;    vector&lt;ofPoint&gt; spherePoints;</div>
<div class="line"><a name="l00176"></a><span class="lineno">  176</span>&#160;</div>
<div class="line"><a name="l00177"></a><span class="lineno">  177</span>&#160;    <a class="code" href="of_constants_8h.html#ae2388165eb5c77ed1edbee0d7d68d4dc">ofFillFlag</a> bFilled;</div>
<div class="line"><a name="l00178"></a><span class="lineno">  178</span>&#160;    <span class="keywordtype">bool</span> bSmoothHinted;</div>
<div class="line"><a name="l00179"></a><span class="lineno">  179</span>&#160;    <a class="code" href="of_constants_8h.html#a52116548570a64993cbe3be944443fce">ofRectMode</a> rectMode;</div>
<div class="line"><a name="l00180"></a><span class="lineno">  180</span>&#160;</div>
<div class="line"><a name="l00181"></a><span class="lineno">  181</span>&#160;    <span class="keywordtype">string</span> filename;</div>
<div class="line"><a name="l00182"></a><span class="lineno">  182</span>&#160;    <a class="code" href="classof_buffer.html">ofBuffer</a> streamBuffer;</div>
<div class="line"><a name="l00183"></a><span class="lineno">  183</span>&#160;    <a class="code" href="classof_pixels__.html">ofPixels</a> imageBuffer;</div>
<div class="line"><a name="l00184"></a><span class="lineno">  184</span>&#160;};</div>
</div><!-- fragment --></div><!-- contents -->

            </div>
      </div>
      <div id="footer">
        ${self.footer()}
      </div> <!-- End Footer -->
    </div> <!-- End Content -->
  </body>
</html>
<%def name="header()">
  <%include file="header.mako" args="active='documentation'" />
</%def>
